version: '2.1'

services:
  
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    depends_on:
      - backend
    image: frontendgo
    ports:
      - 5000:5000

  backend:
    image: backendgo
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=alexis
      - POSTGRES_USER=ale
      - POSTGRES_DATABASE=prueba
      - REDIS_HOST=redisgo
      - REQUEST_ORIGIN=http://localhost:80
    ports:
      - 8081:8080

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    hostname: redisgo

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=alexis
      - POSTGRES_USER=ale
      - POSTGRES_DB=prueba
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: